同步源码于2024年07月12号-07点24分

diff --git a/luci-app-adguardhome/root/etc/init.d/AdGuardHome b/luci-app-adguardhome/root/etc/init.d/AdGuardHome
--- a/luci-app-adguardhome/root/etc/init.d/AdGuardHome
+++ b/luci-app-adguardhome/root/etc/init.d/AdGuardHome
@@ -7,13 +7,13 @@ STOP=01
 
 CONFIGURATION=AdGuardHome
 CRON_FILE=/etc/crontabs/root
-
-extra_command "do_redirect" "0 or 1"
-extra_command "testbackup" "backup or restore"
-extra_command "test_crontab"
-extra_command "force_reload"
-extra_command "isrunning"
-
+GFWSET="gfwlist"
+EXTRA_COMMANDS="do_redirect testbackup test_crontab force_reload isrunning"
+EXTRA_HELP="        do_redirect 0 or 1\
+        testbackup backup or restore\
+		test_crontab
+		force_reload
+		isrunning"
 set_forward_dnsmasq()
 {
 	local PORT="$1"
@@ -29,7 +29,7 @@ set_forward_dnsmasq()
 		if [ "$server" = "$addr" ]; then
 			continue
 		fi
-		# uci add_list dhcp.@dnsmasq[0].server=$server
+		uci add_list dhcp.@dnsmasq[0].server=$server
 	done
 	uci delete dhcp.@dnsmasq[0].resolvfile 2>/dev/null
 	uci set dhcp.@dnsmasq[0].noresolv=1
@@ -48,9 +48,13 @@ stop_forward_dnsmasq()
 	fi
 
 	uci del_list dhcp.@dnsmasq[0].server=$addr 2>/dev/null
+	rcauto="/tmp/resolv.conf.auto"
+	if [ -e "/tmp/resolv.conf.d/resolv.conf.auto" ]; then
+		rcauto="/tmp/resolv.conf.d/resolv.conf.auto"
+	fi
 	addrlist="`uci get dhcp.@dnsmasq[0].server 2>/dev/null`"
 	if [ -z "$addrlist" ] ; then
-		uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.d/resolv.conf.auto 2>/dev/null
+		uci set dhcp.@dnsmasq[0].resolvfile="$rcauto" 2>/dev/null
 		uci delete dhcp.@dnsmasq[0].noresolv 2>/dev/null
 	fi
 	uci commit dhcp
@@ -59,92 +63,60 @@ stop_forward_dnsmasq()
 
 set_iptable()
 {
-	local ipv6_server=$1
-	local tcp_server=$2
-	uci -q batch <<-EOF >/dev/null 2>&1
-	delete firewall.AdGuardHome
-	set firewall.AdGuardHome=include
-	set firewall.AdGuardHome.type=script
-	set firewall.AdGuardHome.path=/usr/share/AdGuardHome/firewall.start
-	set firewall.AdGuardHome.reload=1
-	commit firewall
-EOF
-
-	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
-	for IP in $IPS
-	do
-		if [ "$tcp_server" == "1" ]; then
-			iptables -t nat -I PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-		fi
-		iptables -t nat -I PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-	done
-
-	if [ "$ipv6_server" == 0 ]; then
-		return
+	section=$(uci add firewall redirect)
+	if [ -z "$section" ]; then
+		echo "failed to add redirect rule."
+		exit 1
 	fi
+	uci set firewall.$section.target="DNAT"
+	uci set firewall.$section.name="AdGuard Home"
+	uci set firewall.$section.src="lan"
+	uci set firewall.$section.src_dport="53"
+	uci set firewall.$section.dest_port="$AdGuardHome_PORT"
+	uci commit firewall
+	/etc/init.d/firewall reload
+	echo "firewall rules updated."
 
-	IPS="`ifconfig | grep "inet6 addr" | grep -v " fe80::" | grep -v " ::1" | grep "Global" | awk '{print $3}'`"
-	for IP in $IPS
-	do
-		if [ "$tcp_server" == "1" ]; then
-			ip6tables -t nat -I PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-		fi
-		ip6tables -t nat -I PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-	done
 }
 
 clear_iptable()
 {
-	uci -q batch <<-EOF >/dev/null 2>&1
-	delete firewall.AdGuardHome
-	commit firewall
-EOF
-	local OLD_PORT="$1"
-	local ipv6_server=$2
-	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
-	for IP in $IPS
-	do
-		iptables -t nat -D PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-		iptables -t nat -D PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-	done
-
-	if [ "$ipv6_server" == 0 ]; then
-		return
+	redirects=$(uci show firewall | grep "AdGuard Home" | awk -F".name" '{print $1}')
+	if [ -z "$redirects" ]; then
+		echo "no redirect rules found."
+	else
+		for redirect in $redirects; do
+			uci delete $redirect
+			echo "deleted redirect rule: $redirect"
+		done
+		uci commit firewall
+		/etc/init.d/firewall reload
+		echo "firewall rules updated."
 	fi
-	echo "warn ip6tables nat mod is needed"
-	IPS="`ifconfig | grep "inet6 addr" | grep -v " fe80::" | grep -v " ::1" | grep "Global" | awk '{print $3}'`"
-	for IP in $IPS
-	do
-		ip6tables -t nat -D PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-		ip6tables -t nat -D PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-	done
+
 }
 
 service_triggers() {
 	procd_add_reload_trigger "$CONFIGURATION"
 	[ "$(uci get AdGuardHome.AdGuardHome.redirect)" == "redirect" ] && procd_add_reload_trigger firewall
 }
-
 isrunning(){
-	config_load "${CONFIGURATION}"
-	_isrunning
-	local r=$?
-	([ "$r" == "0" ] && echo "running") || ([ "$r" == "1" ] && echo "not run" ) || echo "no bin"
-	return $r
+config_load "${CONFIGURATION}"
+_isrunning
+local r=$?
+([ "$r" == "0" ] && echo "running") || ([ "$r" == "1" ] && echo "not run" ) || echo "no bin"
+return $r
 }
-
 _isrunning(){
 	config_get binpath $CONFIGURATION binpath "/usr/bin/AdGuardHome"
 	[ ! -f "$binpath" ] && return 2
 	pgrep $binpath 2>&1 >/dev/null && return 0
 	return 1
 }
-
 force_reload(){
 	config_load "${CONFIGURATION}"
 	_isrunning && procd_send_signal "$CONFIGURATION" || start
 }
-
 get_tz()
 {
 	SET_TZ=""
@@ -186,8 +158,6 @@ rm_port53()
 	config_editor "dns.port" "$dnsmasq_port" "$configpath"
 	uci set dhcp.@dnsmasq[0].port="53"
 	uci commit dhcp
-	config_get binpath $CONFIGURATION binpath "/usr/bin/AdGuardHome"
-	killall -9 $binpath
 	/etc/init.d/dnsmasq restart
 }
 
@@ -208,15 +178,13 @@ use_port53()
 	config_editor "dns.port" "53" "$configpath"
 	uci set dhcp.@dnsmasq[0].port="$AdGuardHome_PORT"
 	uci commit dhcp
-	/etc/init.d/dnsmasq reload
+	/etc/init.d/dnsmasq restart
 }
-
 do_redirect()
 {
 	config_load "${CONFIGURATION}"
 	_do_redirect $1
 }
-
 _do_redirect()
 {
 	local section="$CONFIGURATION"
@@ -231,9 +199,6 @@ _do_redirect()
 	fi
 	config_get configpath $CONFIGURATION configpath "/etc/AdGuardHome.yaml"
 	AdGuardHome_PORT=$(config_editor "dns.port" "" "$configpath" "1")
-	if [ ! -s "$configpath" ]; then
-		cp -f /usr/share/AdGuardHome/AdGuardHome_template.yaml $configpath
-	fi
 	if [ -z "$AdGuardHome_PORT" ]; then
 		AdGuardHome_PORT="0"
 	fi
@@ -249,7 +214,7 @@ _do_redirect()
 	if [ "$old_redirect" != "$redirect" ] || [ "$old_port" != "$AdGuardHome_PORT" ] || [ "$old_enabled" = "1" -a "$enabled" = "0" ]; then
 		if [ "$old_redirect" != "none" ]; then
 			if [  "$old_redirect" == "redirect" -a "$old_port" != "0" ]; then
-				clear_iptable "$old_port" "$ipv6_server"
+				clear_iptable
 			elif [ "$old_redirect" == "dnsmasq-upstream" ]; then
 				stop_forward_dnsmasq "$old_port"
 			elif [ "$old_redirect" == "exchange" ]; then
@@ -258,7 +223,7 @@ _do_redirect()
 		fi
 	elif [ "$old_enabled" = "1" -a "$enabled" = "1" ]; then
 		if [  "$old_redirect" == "redirect" -a "$old_port" != "0" ]; then
-			clear_iptable "$old_port" "$ipv6_server"
+			clear_iptable
 		fi
 	fi
 	uci delete AdGuardHome.@AdGuardHome[0].old_redirect 2>/dev/null
@@ -273,14 +238,13 @@ _do_redirect()
 		return 1
 	fi
 	if [ "$redirect" = "redirect" ]; then
-		set_iptable $ipv6_server $tcp_server
+		set_iptable
 	elif [ "$redirect" = "dnsmasq-upstream" ]; then
 		set_forward_dnsmasq "$AdGuardHome_PORT"
 	elif [ "$redirect" == "exchange" -a "$(uci get dhcp.@dnsmasq[0].port 2>/dev/null)" == "53" ]; then
 		use_port53
 	fi
 }
-
 get_filesystem()
 {
 # print out path filesystem
@@ -324,6 +288,7 @@ get_filesystem()
 
 config_editor()
 {
+	[ -n "$3" -a -f $3 ] || return
 	awk -v yaml="$1" -v value="$2" -v file="$3" -v ro="$4" '
 	BEGIN{split(yaml,part,"\.");s="";i=1;l=length(part);}
     {
@@ -368,14 +333,12 @@ testbackup(){
 		restore
 	fi
 }
-
 restore()
 {
 	config_get workdir $CONFIGURATION workdir "/etc/AdGuardHome"
 	config_get backupwdpath $CONFIGURATION backupwdpath "/etc/AdGuardHome"
 	cp -u -r -f $backupwdpath/data $workdir
 }
-
 backup() {
 	config_get backupwdpath $CONFIGURATION backupwdpath "/etc/AdGuardHome"
 	mkdir -p $backupwdpath/data
@@ -403,7 +366,6 @@ backup() {
 		done
 	done
 }
-
 start_service() {
 	# Reading config
 	rm /var/run/AdGserverdis >/dev/null 2>&1
@@ -416,6 +378,7 @@ start_service() {
 		uci set $CONFIGURATION.$CONFIGURATION.hashpass=""
 	fi
 	local enabled
+	local ipst=0
 	config_get_bool enabled $CONFIGURATION enabled 0
 	# update crontab
 	do_crontab
@@ -425,12 +388,16 @@ start_service() {
 	fi
 	#what need to do before reload
 	config_get workdir $CONFIGURATION workdir "/etc/AdGuardHome"
-
+	grep -q "ipset.txt" $configpath 2>/dev/null && ipst=1
+	if [ $ipst -eq 1 ];then
+		ipset list $GFWSET >/dev/null 2>&1 || ipset create $GFWSET hash:ip 2>/dev/null
+	fi
 	config_get backupfile $CONFIGURATION backupfile ""
 	mkdir -p $workdir/data
 	if [ -n "$backupfile" ] && [ ! -d "$workdir/data" ]; then
 		restore
 	fi
+
 	# for overlay data-stk-oo not suppport
 	local cwdfs=$(get_filesystem $workdir)
 	echo "workdir is a $cwdfs filesystem"
@@ -461,7 +428,7 @@ start_service() {
 	config_get upprotect $CONFIGURATION upprotect ""
 	eval upprotect=${upprotect// /\\\\n}
 	echo -e "$upprotect">/lib/upgrade/keep.d/luci-app-adguardhome
-
+	
 	config_get logfile $CONFIGURATION logfile ""
 	if [ -n "$logfile" ]; then
 		ADDITIONAL_ARGS="$ADDITIONAL_ARGS -l $logfile"
@@ -493,7 +460,7 @@ start_service() {
 		_do_redirect 1
 	else
 		_do_redirect 0
-		config_get "redirect" "AdGuardHome" "redirect" "none"
+		config_get "redirect" $CONFIGURATION "redirect" "none"
 		if [ "$redirect" != "none" ]; then
 			procd_open_instance "waitconfig"
 			procd_set_param command "/usr/share/AdGuardHome/watchconfig.sh"
@@ -510,7 +477,6 @@ start_service() {
 	 do_redirect 1
 	fi
 }
-
 reload_service()
 {
 	rm /var/run/AdGlucitest >/dev/null 2>&1
@@ -519,23 +485,22 @@ reload_service()
 }
 
 del_querylog(){
-	local btarget=$(ls $backupwdpath/data | grep -F "querylog.json" | sort -r | head -n 1)
-	local wtarget=$(ls $workdir/data | grep -F "querylog.json" | sort -r | head -n 1)
-	if [ "$btarget"x == "$wtarget"x ]; then
-		[ -z "$btarget" ] && return 1
-		rm -f $workdir/data/$wtarget
-		rm -f $backupwdpath/data/$btarget
-		return 0
-	fi
-	if [ "$btarget" \> "$wtarget" ]; then
-		rm -f $backupwdpath/data/$btarget
-		return 0
-	else
-		rm -f $workdir/data/$wtarget
-		return 0
-	fi
+local btarget=$(ls $backupwdpath/data | grep -F "querylog.json" | sort -r | head -n 1)
+local wtarget=$(ls $workdir/data | grep -F "querylog.json" | sort -r | head -n 1)
+if [ "$btarget"x == "$wtarget"x ]; then
+	[ -z "$btarget" ] && return 1
+	rm -f $workdir/data/$wtarget
+	rm -f $backupwdpath/data/$btarget
+	return 0
+fi
+if [ "$btarget" \> "$wtarget" ]; then
+	rm -f $backupwdpath/data/$btarget
+	return 0
+else
+	rm -f $workdir/data/$wtarget
+	return 0
+fi
 }
-
 stop_service()
 {
 	config_load "${CONFIGURATION}"
@@ -550,19 +515,16 @@ stop_service()
 	echo "AdGuardHome service disabled"
 	touch /var/run/AdGserverdis
 }
-
 boot() {
 	rc_procd boot_service "$@"
 	if eval "type service_started" 2>/dev/null >/dev/null; then
 		service_started
 	fi
 }
-
 test_crontab(){
-	config_load "${CONFIGURATION}"
-	do_crontab
+config_load "${CONFIGURATION}"
+do_crontab
 }
-
 do_crontab(){
 	config_get_bool enabled $CONFIGURATION enabled 0
 	config_get crontab $CONFIGURATION crontab ""
@@ -573,7 +535,7 @@ do_crontab(){
 	default="30 3 * * * /usr/share/AdGuardHome/update_core.sh 2>&1"
 	[ "$enabled" == "0" ] || [ "${crontab//autoupdate/}" == "$crontab" ] && cronenable=0 || cronenable=1
 	crontab_editor
-
+	
 	config_get workdir $CONFIGURATION workdir "/etc/AdGuardHome"
 	config_get lastworkdir $CONFIGURATION lastworkdir "/etc/AdGuardHome"
 	findstr="/usr/share/AdGuardHome/tailto.sh [0-9]* \$(uci get AdGuardHome.AdGuardHome.workdir)/data/querylog.json"
@@ -582,7 +544,7 @@ do_crontab(){
 	[ "$enabled" == "0" ] || [ "${crontab//cutquerylog/}" == "$crontab" ] && cronenable=0 || cronenable=1
 	crontab_editor
 	#[ "$lastworkdir" != "$workdir" ] && uci set AdGuardHome.AdGuardHome.lastworkdir="$workdir" && commit=1
-
+	
 	config_get logfile $CONFIGURATION logfile ""
 	config_get lastlogfile $CONFIGURATION lastlogfile ""
 	findstr="/usr/share/AdGuardHome/tailto.sh [0-9]* \$(uci get AdGuardHome.AdGuardHome.logfile)"
@@ -591,7 +553,7 @@ do_crontab(){
 	[ "$logfile" == "syslog" ] || [ "$logfile" == "" ] || [ "$enabled" == "0" ] || [ "${crontab//cutruntimelog/}" == "$crontab" ] && cronenable=0 || cronenable=1
 	crontab_editor
 	#[ -n "$logfile" ] && [ "$lastlogfile" != "$logfile" ] && uci set AdGuardHome.AdGuardHome.lastlogfile="$logfile" && commit=1
-
+	
 	findstr="/usr/share/AdGuardHome/addhost.sh"
 	default="0 * * * * /usr/share/AdGuardHome/addhost.sh"
 	[ "$enabled" == "0" ] || [ "${crontab//autohost/}" == "$crontab" ] && cronenable=0 || cronenable=1
@@ -602,10 +564,14 @@ do_crontab(){
 	default="30 3 * * * /usr/share/AdGuardHome/gfw2adg.sh"
 	[ "$enabled" == "0" ] || [ "${crontab//autogfw/}" == "$crontab" ] && cronenable=0 || cronenable=1
 	crontab_editor
+
+	findstr="/usr/share/AdGuardHome/gfwipset2adg.sh"
+	default="31 3 * * * /usr/share/AdGuardHome/gfwipset2adg.sh"
+	[ "$enabled" == "0" ] || [ "${crontab//autogfwipset/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
 	[ "$cronreload" -gt 0 ] && /etc/init.d/cron restart
 	#[ "$commit" -gt 0 ] && uci commit AdGuardHome
 }
-
 crontab_editor(){
 	#usage input:
 	#findstr=
@@ -615,7 +581,7 @@ crontab_editor(){
 	#output:cronreload:if >1 please /etc/init.d/cron restart manual
 	local testline reload
 	local line="$(grep "$findstr" $CRON_FILE)"
-	[ -n "$replace" ] && [ -n "$line" ] && eval testline="\${line//$replace}" && [ "$testline" != "$line" ] && line="$testline" && reload="1" && replace=""
+	[ -n "$replace" ] && [ -n "$line" ] && eval testline="\${line//$replace}" && [ "$testline" != "$line" ] && line="$testline" && reload="1" && replace="" 
 	if [ "${line:0:1}" != "#" ]; then
 		if [ $cronenable -eq 1 ]; then
 			[ -z "$line" ] && line="$default" && reload="1"
@@ -639,4 +605,5 @@ crontab_editor(){
 			echo "$line" >> $CRON_FILE
 		fi
 	fi
+	
 }
