同步源码于2023年07月23号-20点50分

diff --git a/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -1,7 +1,7 @@
 #!/bin/sh /etc/rc.common
 # SPDX-License-Identifier: GPL-3.0-only
 #
-# Copyright (C) 2019-2022 Tianling Shen <cnsztl@immortalwrt.org>
+# Copyright (C) 2019-2023 Tianling Shen <cnsztl@immortalwrt.org>
 
 USE_PROCD=1
 
@@ -9,13 +9,8 @@ START=99
 STOP=10
 
 NAME="unblockneteasemusic"
-UPGRADE_CONF="/lib/upgrade/keep.d/$NAME"
-
-IPT_N="iptables -t nat"
-
-FW4="$(command -v fw4)"
-RULES_UC="/usr/share/$NAME/rules/default.uc"
-RULES_NFT="/etc/nftables.d/90-$NAME-rules.nft"
+UNM_DIR="/usr/share/$NAME"
+RUN_DIR="/var/run/$NAME"
 
 is_enabled() {
 	local enabled
@@ -50,34 +45,23 @@ append_param_boolenv() {
 append_filter_client() {
 	local cfg="$1"
 
-	local ip_addr filter_mode
-	config_get ip_addr "$cfg" "ip_addr"
+	is_enabled "$cfg" "enable" || return 1
+
+	local mac_addr filter_mode
+	config_get mac_addr "$cfg" "mac_addr"
 	config_get filter_mode "$cfg" "filter_mode"
-	[ -n "$ip_addr" -a -n "$filter_mode" ] || return 1
+	[ -n "$mac_addr" -a -n "$filter_mode" ] || return 1
 
 	case "${filter_mode}" in
 	"disable_http")
-		if [ -n "$FW4" ]; then
-			acl_http_addr="${acl_http_addr:+$acl_http_addr\n}${ip_addr}"
-		else
-			ipset -! add "acl_neteasemusic_http" "${ip_addr}"
-		fi
+		acl_http_addr="${acl_http_addr:+$acl_http_addr\n}${mac_addr}"
 		;;
 	"disable_https")
-		if [ -n "$FW4" ]; then
-			acl_https_addr="${acl_https_addr:+$acl_https_addr\n}${ip_addr}"
-		else
-			ipset -! add "acl_neteasemusic_https" "${ip_addr}"
-		fi
+		acl_https_addr="${acl_https_addr:+$acl_https_addr\n}${mac_addr}"
 		;;
 	"disable_all")
-		if [ -n "$FW4" ]; then
-			acl_http_addr="${acl_http_addr:+$acl_http_addr\n}${ip_addr}"
-			acl_https_addr="${acl_https_addr:+$acl_https_addr\n}${ip_addr}"
-		else
-			ipset -! add "acl_neteasemusic_http" "${ip_addr}"
-			ipset -! add "acl_neteasemusic_https" "${ip_addr}"
-		fi
+		acl_http_addr="${acl_http_addr:+$acl_http_addr\n}${mac_addr}"
+		acl_https_addr="${acl_https_addr:+$acl_https_addr\n}${mac_addr}"
 		;;
 	esac
 }
@@ -89,49 +73,31 @@ start_service() {
 	local update_time
 	config_get update_time "config" "update_time" "3"
 	sed -i "/$NAME/d" /etc/crontabs/root
-	is_enabled "config" "auto_update" && echo "0 ${update_time} * * * /usr/share/$NAME/update.sh update_core" >> "/etc/crontabs/root"
-	echo "*/5 * * * * /usr/share/$NAME/log_check.sh" >> "/etc/crontabs/root"
+	echo -e "30 2 * * * /etc/init.d/unblockneteasemusic restart" >> "/etc/crontabs/root"
+	! is_enabled "config" "auto_update" || echo -e "0 ${update_time} * * * $UNM_DIR/update.sh update_core" >> "/etc/crontabs/root"
 	/etc/init.d/cron restart
 
-	[ ! -s "/usr/share/$NAME/core/app.js" ] && { rm -f "/usr/share/$NAME/local_ver"; sh "/usr/share/$NAME/update.sh" "update_core_non_restart"; }
-	[ ! -s "/usr/share/$NAME/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "/tmp/$NAME.log"; exit 1; }
+	mkdir -p "$RUN_DIR"
+	[ -s "$UNM_DIR/core/app.js" ] || { rm -f "$UNM_DIR/local_ver"; sh "$UNM_DIR/update.sh" "update_core_non_restart"; }
+	[ -s "$UNM_DIR/core/app.js" ] || { echo "Core Not Found, please download it before starting." >> "$RUN_DIR/run.log"; return 1; }
 
 	procd_open_instance "$NAME"
-	procd_set_param command node "/usr/share/$NAME/core/app.js"
-	append_param "-a" "0.0.0.0"
+	procd_set_param command node "$UNM_DIR/core/app.js"
+	append_param "-a" "::"
 
 	local http_port https_port hijack_ways
 	config_get http_port "config" "http_port" "5200"
 	config_get https_port "config" "https_port" "5201"
 	config_get hijack_ways "config" "hijack_ways" "use_ipset"
-	[ "${hijack_ways}" = "use_hosts" ] && { http_port="80"; https_port="443"; }
+	[ "$hijack_ways" != "use_hosts" ] || { http_port="80"; https_port="443"; }
 	append_param "-p" "${http_port}":"${https_port}"
 
-	if [ -n "$FW4" ]; then
-		json_init
-		if is_enabled "config" "pub_access"; then
-			json_add_int o_pub_access "1"
-		else
-			json_add_int o_pub_access "0"
-		fi
-		json_add_int o_http_port "${http_port}"
-		json_add_int o_https_port "${https_port}"
-		json_add_string o_hijack_ways "${hijack_ways}"
-	else
-		if is_enabled "config" "pub_access"; then
-			iptables -I "INPUT" -p "tcp" --dport "${http_port}" -j "ACCEPT"
-			iptables -I "INPUT" -p "tcp" --dport "${https_port}" -j "ACCEPT"
-			echo "${http_port}:${https_port}" > "/tmp/$NAME.ports"
+	json_init
+	json_add_int http_port "${http_port}"
+	json_add_int https_port "${https_port}"
+	json_add_string hijack_ways "${hijack_ways}"
 
-			mkdir -p "/var/etc/"
-			echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
-		fi
-	fi
-
-	local music_source
-	config_get music_source "config" "music_source" "default"
-	[ "${music_source}" != "default" ] && append_param -o "${music_source}"
-
+	append_param_arg "config" "music_source" "-o"
 	append_param_arg "config" "cnrelay" "-c"
 	append_param_arg "config" "endpoint_url" "-e" "https://music.163.com"
 	append_param_arg "config" "netease_server_ip" "-f"
@@ -140,21 +106,24 @@ start_service() {
 
 	local log_level
 	config_get log_level "config" "log_level" "info"
-	procd_set_param env LOG_FILE="/tmp/$NAME.log"
+	procd_set_param env LOG_FILE="$RUN_DIR/run.log"
 	procd_append_param env LOG_LEVEL="$log_level"
 
 	append_param_env "config" "joox_cookie" "JOOX_COOKIE"
+	append_param_env "config" "kuwo_cookie" "KUWO_COOKIE"
 	append_param_env "config" "migu_cookie" "MIGU_COOKIE"
 	append_param_env "config" "qq_cookie" "QQ_COOKIE"
 	append_param_env "config" "youtube_key" "YOUTUBE_KEY"
-	append_param_env "config" "self_issue_cert_crt" "SIGN_CERT" "/usr/share/$NAME/core/server.crt"
-	append_param_env "config" "self_issue_cert_key" "SIGN_KEY" "/usr/share/$NAME/core/server.key"
+	append_param_env "config" "self_issue_cert_crt" "SIGN_CERT" "$UNM_DIR/core/server.crt"
+	append_param_env "config" "self_issue_cert_key" "SIGN_KEY" "$UNM_DIR/core/server.key"
+	append_param_env "config" "local_vip" "ENABLE_LOCAL_VIP"
 
 	append_param_boolenv "config" "follow_source_order" "FOLLOW_SOURCE_ORDER"
 	append_param_boolenv "config" "search_album" "SEARCH_ALBUM"
 	append_param_boolenv "config" "enable_flac" "ENABLE_FLAC"
-	append_param_boolenv "config" "local_vip" "ENABLE_LOCAL_VIP"
+	append_param_boolenv "config" "select_max_br" "SELECT_MAX_BR"
 	append_param_boolenv "config" "disable_upgrade_check" "DISABLE_UPGRADE_CHECK"
+	append_param_boolenv "config" "block_ads" "BLOCK_ADS"
 	case "$(config_get "config" "replace_music_source")" in
 		"lower_than_192kbps") procd_append_param env MIN_BR="192000" ;;
 		"lower_than_320kbps") procd_append_param env MIN_BR="320000" ;;
@@ -167,58 +136,55 @@ start_service() {
 	procd_set_param respawn
 
 	local lan_addr="$(uci -q get network.lan.ipaddr)"
-	local tmp="/tmp/$NAME"
 	if [ "${hijack_ways}" = "use_ipset" ]; then
-		local settype nftflag
-		if [ -n "$FW4" ]; then
-			settype="nftset"
-			nftflag="inet#fw4#"
-		else
-			settype="ipset"
-		fi
 		mkdir -p "/tmp/dnsmasq.d"
 		rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
 		cat <<-EOF > "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
 			dhcp-option=252,http://${lan_addr}:${http_port}/proxy.pac
-			${settype}=/.music.163.com/${nftflag}neteasemusic
-			${settype}=/interface.music.163.com/${nftflag}neteasemusic
-			${settype}=/interface3.music.163.com/${nftflag}neteasemusic
-			${settype}=/apm.music.163.com/${nftflag}neteasemusic
-			${settype}=/apm3.music.163.com/${nftflag}neteasemusic
-			${settype}=/clientlog.music.163.com/${nftflag}neteasemusic
-			${settype}=/clientlog3.music.163.com/${nftflag}neteasemusic
+			nftset=/.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/interface.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/interface3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/apm.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/apm3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/clientlog.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
+			nftset=/clientlog3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
 		EOF
-		/etc/init.d/dnsmasq reload
+		/etc/init.d/dnsmasq restart 2>"/dev/null"
 
-		[ -n "$FW4" ] || {
-			ipset create "acl_neteasemusic_http" hash:ip
-			ipset create "acl_neteasemusic_https" hash:ip
-			ipset create "neteasemusic" hash:ip
-		}
 		config_foreach append_filter_client "acl_rule"
 
-		local netease_music_ips="$(uclient-fetch -qO- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*')"
-		local netease_music_ips2="$(uclient-fetch -qO- "https://music.httpdns.c.163.com/d" --post-data="music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.dns.*["ips"].*')"
-		if [ -n "$FW4" ]; then
-			local neteasemusic_addr="$(echo -e "${netease_music_ips}\n${netease_music_ips2}" | sort -u | awk '{print $1}')"
+		local netease_music_ips="$(wget -qO- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*')"
+		local netease_music_ips2="$(wget -qO- "https://music.httpdns.c.163.com/d" --post-data="music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.dns.*["ips"].*')"
+		json_add_string acl_http_addr "$(echo -e "${acl_http_addr}" | sort -u)"
+		json_add_string acl_https_addr "$(echo -e "${acl_https_addr}" | sort -u)"
+		json_add_string neteasemusic_addr "$(echo -e "${netease_music_ips}\n${netease_music_ips2}" | sort -u)"
 
-			json_add_string o_acl_http_addr "$(echo -e "${acl_http_addr}" | sort -u | awk '{print $1}')"
-			json_add_string o_acl_https_addr "$(echo -e "${acl_https_addr}" | sort -u | awk '{print $1}')"
-			json_add_string o_neteasemusic_addr "$neteasemusic_addr"
-		else
-			echo -e "${netease_music_ips}\n${netease_music_ips2}" | sort -u | awk '{print "ipset add neteasemusic "$1}' | sh
+		json_dump > "$RUN_DIR/fw4.info"
+		json_cleanup
+		utpl -F "$RUN_DIR/fw4.info" -S "$UNM_DIR/nftables.ut" > "$RUN_DIR/fw4.nft"
 
-			$IPT_N -N "netease_cloud_music"
-			for local_addr in "0.0.0.0/8" "10.0.0.0/8" "127.0.0.0/8" "169.254.0.0/16" "172.16.0.0/12" "192.168.0.0/16" "224.0.0.0/4" "240.0.0.0/4"; do
-				$IPT_N -A "netease_cloud_music" -d "${local_addr}" -j "RETURN"
-			done
+		if is_enabled "config" "pub_access"; then
+			procd_open_data
+			json_add_array firewall
+				json_add_object ""
+				json_add_string type rule
+				json_add_string name "Allow-access-UNM-http-$http_port"
+				json_add_string src "*"
+				json_add_string dest_port "$http_port"
+				json_add_string proto tcp
+				json_add_string target ACCEPT
+				json_close_object
 
-			$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_http" "src" --dport "80" -j "REDIRECT" --to-ports "${http_port}"
-			$IPT_N -A "netease_cloud_music" -p "tcp" -m "set" ! --match-set "acl_neteasemusic_https" "src" --dport "443" -j "REDIRECT" --to-ports "${https_port}"
-			$IPT_N -I "PREROUTING" -p "tcp" -m "set" --match-set "neteasemusic" "dst" -j "netease_cloud_music"
-
-			mkdir -p "/var/etc/"
-			echo "/etc/init.d/$NAME restart" > "/var/etc/$NAME.include"
+				json_add_object ""
+				json_add_string type rule
+				json_add_string name "Allow-access-UNM-https-$https_port"
+				json_add_string src "*"
+				json_add_string dest_port "$https_port"
+				json_add_string proto tcp
+				json_add_string target ACCEPT
+				json_close_object
+			json_close_array
+			procd_close_data
 		fi
 	elif [ "${hijack_ways}" = "use_hosts" ]; then
 		mkdir -p "/tmp/dnsmasq.d"
@@ -234,22 +200,20 @@ start_service() {
 			address=/clientlog3.music.163.com/${lan_addr}
 			address=/music.httpdns.c.163.com/0.0.0.0
 		EOF
-		/etc/init.d/dnsmasq reload
-
-		ip route add "223.252.199.10" dev lo
-	fi
-
-	if [ -n "$FW4" ]; then
-		json_dump -i >"$tmp.json"
-		if utpl -F "$tmp.json" -S "$RULES_UC" > "$tmp.nft" && ! cmp -s "$tmp.nft" "$RULES_NFT"; then
-			echo "table inet chk {include \"$tmp.nft\";}" > "$tmp.nft.chk"
-			! nft -f "$tmp.nft.chk" -c || { mv -f "$tmp.nft" "$RULES_NFT"; fw4 reload; }
-		fi
-		rm -f "$tmp.json" "$tmp.nft" "$tmp.nft.chk"
+		/etc/init.d/dnsmasq restart 2>"/dev/null"
 	fi
 
 	procd_close_instance
-} >"/dev/null" 2>&1
+
+	procd_open_instance "log-check"
+	procd_set_param command "$UNM_DIR/log_check.sh"
+	procd_set_param respawn
+	procd_close_instance
+}
+
+service_started() {
+	procd_set_config_changed firewall
+}
 
 stop_service() {
 	config_load "$NAME"
@@ -257,56 +221,28 @@ stop_service() {
 	sed -i "/$NAME/d" "/etc/crontabs/root"
 	/etc/init.d/cron restart
 
-	rm -f "${UPGRADE_CONF}"
-	is_enabled "config" "keep_core_when_upgrade" && {
-		echo "/usr/share/$NAME/core/" >> "${UPGRADE_CONF}"
-		echo "/usr/share/$NAME/local_ver" >> "${UPGRADE_CONF}"
-	}
-
-	local self_issue_cert_crt self_issue_cert_key
-	config_get "self_issue_cert_crt" "config" "self_issue_cert_crt"
-	config_get "self_issue_cert_key" "config" "self_issue_cert_key"
-	{ [ -f "${self_issue_cert_crt}" ] && [ -f "${self_issue_cert_key}" ]; } && {
-		echo "${self_issue_cert_crt}" >> "${UPGRADE_CONF}"
-		echo "${self_issue_cert_key}" >> "${UPGRADE_CONF}"
-	}
-
 	local chain settable
-	if [ -n "$FW4" ]; then
-		for chain in "netease_cloud_music_redir" "netease_cloud_music"; do
-			nft flush chain inet fw4 "$chain"
-		done
-		for settable in "acl_neteasemusic_http" "acl_neteasemusic_https" "local_addr" "neteasemusic"; do
-			nft flush set inet fw4 "$set"
-		done
+	for chain in "netease_cloud_music_redir" "netease_cloud_music"; do
+		nft flush chain inet fw4 "$chain" 2>"/dev/null"
+		nft delete chain inet fw4 "$chain" 2>"/dev/null"
+	done
+	for settable in "acl_neteasemusic_http" "acl_neteasemusic_https" "neteasemusic" "neteasemusic6"; do
+		nft flush set inet fw4 "$settable" 2>"/dev/null"
+		nft delete set inet fw4 "$settable" 2>"/dev/null"
+	done
 
-		rm -f "$RULES_NFT"
-		fw4 reload
-	else
-		[ ! -e "/tmp/$NAME.ports" ] || {
-			iptables -D "INPUT" -p "tcp" --dport "$(awk -F ':' '{print $1}' "/tmp/$NAME.ports")" -j "ACCEPT"
-			iptables -D "INPUT" -p "tcp" --dport "$(awk -F ':' '{print $2}' "/tmp/$NAME.ports")" -j "ACCEPT"
-		}
-		rm -f "/tmp/$NAME.ports"
-
-		$IPT_N -D "PREROUTING" -p "tcp" -m set --match-set "neteasemusic" "dst" -j "netease_cloud_music"
-		$IPT_N -F "netease_cloud_music"
-		$IPT_N -X "netease_cloud_music"
-
-		for settable in "acl_neteasemusic_http" "acl_neteasemusic_https" "local_addr" "neteasemusic"; do
-			ipset destroy "$settable"
-		done
-
-		echo "" > "/var/etc/$NAME.include"
-	fi
+	rm -f "$RUN_DIR/fw4.info"
+	echo > "$RUN_DIR/fw4.nft"
 
 	rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-	/etc/init.d/dnsmasq reload
+	/etc/init.d/dnsmasq restart 2>"/dev/null"
 
-	ip route del "223.252.199.10"
+	rm -f "$RUN_DIR/run.log"
+}
 
-	rm -f "/tmp/$NAME.log"
-} >"/dev/null" 2>&1
+service_stopped() {
+	procd_set_config_changed firewall
+}
 
 reload_service() {
 	stop
