同步源码于2026年08月24号-07点31分

diff --git a/relevance/docker/Makefile b/relevance/docker/Makefile
--- a/relevance/docker/Makefile
+++ b/relevance/docker/Makefile
@@ -1,8 +1,8 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=docker
-PKG_VERSION:=29.1.1
-PKG_RELEASE:=$(AUTORELEASE)
+PKG_VERSION:=29.6.1
+PKG_RELEASE:=1
 PKG_LICENSE:=Apache-2.0
 PKG_LICENSE_FILES:=LICENSE
 
@@ -10,30 +10,33 @@ PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_GIT_URL:=github.com/docker/cli
 PKG_GIT_REF:=v$(PKG_VERSION)
 PKG_SOURCE_URL:=https://codeload.$(PKG_GIT_URL)/tar.gz/$(PKG_GIT_REF)?
-PKG_HASH:=a02081b7d6fb10bfbc8afb621e7edc5124048b31eea7a1ab73c7ccd924b03a66
-PKG_GIT_SHORT_COMMIT:=0aedba5 # SHA1 used within the docker executables
+PKG_HASH:=74d14dd212b07cd3328989dc6a029dde2ebbe6a878199eaaafad54916f456194
+PKG_GIT_SHORT_COMMIT:=8900f1d # SHA1 used within the docker executables
 
 PKG_MAINTAINER:=Gerard Ryan <G.M0N3Y.2503@gmail.com>
 
-PKG_BUILD_DEPENDS:=golang/host
+PKG_BUILD_DEPENDS:=golang/host dockerd
 PKG_BUILD_PARALLEL:=1
-PKG_USE_MIPS16:=0
 
 GO_PKG:=$(PKG_GIT_URL)
 
 include $(INCLUDE_DIR)/package.mk
 include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk
 
+EMPTY:=
+SPACE:=$(EMPTY) $(EMPTY)
+ARCH_DEPENDS:=@($(subst $(SPACE),||,$(strip $(filter-out mips mips64 mipsel mips64el,$(subst ||,$(SPACE),$(patsubst @(%),%,$(GO_ARCH_DEPENDS)))))))
+
 define Package/docker
   SECTION:=utils
   CATEGORY:=Utilities
   TITLE:=Docker Community Edition CLI
   URL:=https://www.docker.com/
-  DEPENDS:=$(GO_ARCH_DEPENDS)
+  DEPENDS:=$(ARCH_DEPENDS)
 endef
 
 define Package/docker/description
-The CLI used in the Docker CE and Docker EE products.
+  The CLI used in the Docker CE and Docker EE products.
 endef
 
 GO_PKG_INSTALL_EXTRA:=\
@@ -44,27 +47,24 @@ TAR_OPTIONS:=--strip-components 1 $(TAR_OPTIONS)
 TAR_CMD=$(HOST_TAR) -C $(1) $(TAR_OPTIONS)
 TARGET_LDFLAGS += $(if $(CONFIG_USE_GLIBC),-lc -lgcc_eh)
 
+# Verify PKG_GIT_SHORT_COMMIT
 define Build/Prepare
 	$(Build/Prepare/Default)
 
-	# Verify PKG_GIT_SHORT_COMMIT
-	( \
-		EXPECTED_PKG_GIT_SHORT_COMMIT=$$$$( $(CURDIR)/../dockerd/git-short-commit.sh '$(PKG_GIT_URL)' '$(PKG_GIT_REF)' '$(TMP_DIR)/git-short-commit/$(PKG_NAME)-$(PKG_VERSION)' ); \
-		if [ "$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}" != "$(strip $(PKG_GIT_SHORT_COMMIT))" ]; then \
-			echo "ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}', found 'PKG_GIT_SHORT_COMMIT:=$(strip $(PKG_GIT_SHORT_COMMIT))'"; \
-			exit 1; \
-		fi \
-	)
+	EXPECTED_PKG_GIT_SHORT_COMMIT=$$$$( $(CURDIR)/../dockerd/git-short-commit.sh '$(PKG_GIT_URL)' '$(PKG_GIT_REF)' '$(TMP_DIR)/git-short-commit/$(PKG_NAME)-$(PKG_VERSION)' ); \
+	if [ "$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}" != "$(strip $(PKG_GIT_SHORT_COMMIT))" ]; then \
+		echo "ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}', found 'PKG_GIT_SHORT_COMMIT:=$(strip $(PKG_GIT_SHORT_COMMIT))'"; \
+		exit 1; \
+	fi
 endef
 
 define Build/Compile
-	( \
-		cd $(PKG_BUILD_DIR); \
-		$(GO_PKG_VARS) \
-		GITCOMMIT=$(PKG_GIT_SHORT_COMMIT) \
-		VERSION=$(PKG_VERSION) \
-		./scripts/build/binary; \
-	)
+	cd $(PKG_BUILD_DIR); \
+	$(GO_PKG_VARS) \
+	GITCOMMIT=$(PKG_GIT_SHORT_COMMIT) \
+	VERSION=$(PKG_VERSION) \
+	TARGET=$(PKG_BUILD_DIR)/build \
+	./scripts/build/binary
 endef
 
 define Package/docker/install
